spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: data-verification
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/dataspace?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 8cyseelefh
  mail:
    host: smtp.163.com
    password: XKiBDwDUzcmU27UU
    port: 465
    username: 17634565665@163.com
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.com.booking.bean
server:
  port: 8888
ipfs:
  config:
    multi-addr: /ip4/127.0.0.1/tcp/5001
